dist: xenial
language: node_js

node_js:
  - lts/*
  - node

notifications:
  email:
    on_failure: change

before_install:
  - npm install -g npm@latest

cache: npm

deploy:
  provider: npm
  email: remi@cliqz.com
  skip_cleanup: true
  api_key:
    secure: tpCPNABswO9sXKN8d7oQx3+5yoPlnbvMAJ2XcV7sUsowq7463sQPpBZ8hTmbrmGy+9+i8NAqB9/+8nTF3yu8mGA+NTbsJ0o0sSK3hHuRmXACCmaetXW8e8LZ1B3UwhXa25Qr+F3jx6EPcDkcBij1+lRQxC/pYsVjiCDw/I2LNvLT7WBHuS5CQTvjIGQMxgK7PIHNDrEYZax8PBKWGXRp06c2l1S1aRECb73PKPdU8afTZCMXKKxC3ElPxSe8C5wziQuItWN48VQVj5vZYSroN2fDi/SoTK4Mj4vTLnYzQhLhhkTRtuW5MUc91xQhcT0m/DDq8Rbg3P+xtMtMG1FDw47hSMWQpXP1sMxreb9ROQSwc0acWP/rOVqvFypHXarRUYvfhHU6ptzlPUVdE7kCHiMxVxR0VrpBaLShwELo3h9ypa4Hy/GFwMZ0tQXpWOQAcEgGbtblyy8nyH/ghUaFpwNlBbK3Hr2plEq4b/RtU8yhit+NDSzXbdpetW2gbmWVuEgMQW4RudJxZMZws7Bf12BPaBDnqwiLSzDulkh4WeG/ZscwN/zmum++4gTUa0beX54Pvn0b2S0Dsfn33iQJ3NQNFdCikpWpV+d4Tu8tLLrZf+ePoGhXHvs2PSYlpQdd+WPic1wUuiiu0S7O4pogLYMls5IYUCTHJmu9ORPYCJc=
  on:
    branch: master
    tags: true
    repo: remusao/tsmaz
